name: Deploy Dev to Vercel Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  Deploy-Preview:
    if: github.repository == 'Virtality-app/virtality-platform'
    runs-on: ubuntu-latest

    steps:
      - name: Runner Setup
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: '10.23.0'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Console Environment Information
        run: vercel pull --cwd ./apps/console --yes --environment=preview --token=$VERCEL_TOKEN --project=$VERCEL_PROJECT_ID

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --cwd ./apps/console --token=$VERCEL_TOKEN --project=$VERCEL_PROJECT_ID
